#!/usr/bin/env sh

set -e

timestamp=$(date +%Y-%m-%d_%H.%M.%S)

echo "INFO: Moving PostgreSQL data into postgresql/data.${timestamp}.." >&2
mv postgresql/data postgresql/data.${timestamp}

echo "INFO: Moving uploads data into gitlab/public/uploads.${timestamp}.." >&2
mv gitlab/public/uploads gitlab/public/uploads.${timestamp}

echo "INFO: Moving repository data into repositories.${timestamp}.." >&2
mv repositories repositories.${timestamp}
mkdir repositories
mv repositories.${timestamp}/.gitkeep repositories/
