#!/usr/bin/env ruby
#
# frozen_string_literal: true

success = true
system(*%w[gdk start postgresql-geo])

[
  %w[bundle exec rails db:setup:geo]
].each do |cmd|
  success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *cmd, chdir: 'gitlab')
end

exit true if success

abort "#{$PROGRAM_NAME} failed"
