#!/usr/bin/env ruby

require_relative '../lib/gdk'

def postgresql
  @postgresql ||= config.geo.enabled? ? GDK::PostgresqlGeo.new : GDK::Postgresql.new
end

def config
  @config ||= GDK::Config.new
end

def main
  abort 'postgres not ready' unless postgresql.ready?

  dbname = config.praefect.database.dbname

  exit if postgresql.db_exists?(dbname)

  abort 'createdb failed' unless postgresql.createdb(%W[--encoding=UTF8 --locale=C --echo #{dbname}])

  abort 'migrate failed' unless system('support/migrate-praefect')
end

main
