#!/usr/bin/env ruby
require_relative '../lib/gdk'

system(*%w[gdk start postgresql])

postgresql = GDK::PostgreSQL.new
abort 'postgres not ready' unless postgresql.ready?

abort 'createdb failed' unless postgresql.createdb(['grafana'])
