#!/usr/bin/env ruby
#
# frozen_string_literal: true

require 'pathname'
require 'yaml'

path = Pathname.new('elasticsearch/config/elasticsearch.yml')
exit 1 unless path.exist?

config = YAML.load_file(path, fallback: {})

# Elastic settings can be dotpaths or nested yaml
security_enabled = config['xpack.security.enabled']
security_enabled = config.dig('xpack', 'security', 'enabled') if security_enabled.nil?

# Disable security if no setting exists
if security_enabled.nil?
  File.open(path, 'a') do |f|
    f.puts 'xpack.security.enabled: false'
  end
end
