#!/usr/bin/env ruby
#
# frozen_string_literal: true

# This script implements 'cd foo && exec bar' without the need to invoke
# /bin/sh for the ' && '.

require_relative '../lib/gdk'

abort "Usage: #{$PROGRAM_NAME} DIRECTORY COMMAND [ARGUMENTS ...]" if ARGV.count < 2

Dir.chdir(ARGV.shift)

args = ARGV.join(' ')
shell = ENV['SHELL'] || '/bin/sh'
cmd = [shell, '-l', '-c', args]

exec(*cmd)
