#!/usr/bin/env ruby

EXEC = 'geo_log_cursor'.freeze

bin_dir = 'gitlab/ee/bin/'
bin_dir = 'gitlab/bin' unless File.exist?(File.join(bin_dir, EXEC))

abort 'Could not locate Geo log cursor executable' unless File.exist?(File.join(bin_dir, EXEC))

Dir.chdir(bin_dir)

exec("./#{EXEC}", *ARGV)
