#!/usr/bin/env ruby
# frozen_string_literal: true

require 'parallel'
require_relative '../lib/gdk'

tasks = ARGV

Parallel.each(tasks, in_threads: 4) do |task|
  GDK.make(task, env: ENV, command_prefix: "[#{task}] ")
end
