#!/usr/bin/env ruby
#
# frozen_string_literal: true

require_relative '../lib/gdk'

upgrader = GDK::PostgresqlUpgrader.new
dir = upgrader.bin_path

raise('ERROR: Unable to determine PostgreSQL bin directory') unless dir

puts dir
