#!/usr/bin/env ruby
#
# frozen_string_literal: true

require 'mkmf'
require 'pathname'
require_relative '../lib/shellout'

MakeMakefile::Logging.quiet = true
MakeMakefile::Logging.logfile(File::NULL)

POSTGRESQL_VERSIONS = [12, 11, 10, 9.6].freeze

def brew_linked_discover
  dirname_if_exists_for(find_executable('postgres'))
end

def brew_symlink_discover
  POSTGRESQL_VERSIONS.each do |version|
    pg_bin_dir = dirname_if_exists_for("/usr/local/opt/postgresql@#{version}/bin/postgres")

    return pg_bin_dir if pg_bin_dir
  end

  nil
end

def brew_cellar_discover
  brew_cellar_prefix = Shellout.new('brew --cellar').try_run

  POSTGRESQL_VERSIONS.each do |version|
    brew_cellar_pg = "#{brew_cellar_prefix}/postgresql@#{version}"

    next if brew_cellar_pg.empty?

    brew_cellar_pg_bin = Dir.glob(File.join(brew_cellar_pg, '/*/bin'))
    return brew_cellar_pg_bin.last if brew_cellar_pg_bin.any?
  end

  nil
end

def pg_config_discover
  Shellout.new(%w[pg_config --bindir]).run
rescue Errno::ENOENT
  nil
end

def dirname_if_exists_for(path)
  return unless path

  path = Pathname.new(path)

  return unless path.exist?

  path.dirname
end

dir = (brew_linked_discover || brew_symlink_discover || brew_cellar_discover || pg_config_discover)

raise('ERROR: Unable to determine PostgreSQL bin directory') unless dir

puts dir
