#!/bin/sh

set -e # exit on uncaught failure

gitlab_base_url="https://gitlab.com"
gitlab="gitlab"
gitlab_org="gitlab-org"
remote_name="upstream"
default_branch="main"

cd ./gitlab

git_remote_add_upstream() {
  echo "Remote origin is ${1}, adding remote ${remote_name} to ${1}"
  git remote add "${remote_name}" "${gitlab_base_url}/${gitlab_org}/${1}.git"
}

grep_git_remote() {
  git remote -v | grep -q "${1}\.git.*$"
}

if git remote | grep -q "^${remote_name}$"; then
  echo "Remote ${remote_name} already exists in $(pwd). Exiting."
  exit 0
fi

# Try to determine if remote should be ee or ce

git_remote_add_upstream ${gitlab}

git remote set-url --push "${remote_name}" none # make 'upstream' fetch-only
echo "Fetching ${default_branch} from ${remote_name}..."

if [ -n "${GIT_CURL_VERBOSE}" ]; then
  GIT_CURL_VERBOSE=1 git fetch "${remote_name}" ${default_branch}
else
  git fetch "${remote_name}" ${default_branch}
fi

# check if the default branch already exists
if git show-ref --verify --quiet refs/heads/${default_branch}; then
  git branch --set-upstream-to="${remote_name}/${default_branch}" ${default_branch}
else
  git branch ${default_branch} "${remote_name}/${default_branch}"
fi
