#!/usr/bin/env ruby
#
# frozen_string_literal: true

require_relative '../lib/gdk'

url = ARGV[0] || GDK::TestURL.default_url
verbose = ENV['QUIET'] == 'false'

begin
  exit(GDK::TestURL.new(url).wait(verbose: verbose))
rescue GDK::TestURL::UrlAppearsInvalid
  GDK::Output.error("'#{url}' does not appear to be a valid URL?")
  exit(1)
end
