#!/usr/bin/env ruby
#
# frozen_string_literal: true

require_relative '../lib/gdk'

url = ARGV[0] || GDK::TestURL.default_url
verbose = ENV['QUIET'] == 'false'

begin
  exit(GDK::TestURL.new(url).wait(verbose:))
rescue GDK::TestURL::UrlAppearsInvalid => e
  GDK::Output.error("'#{url}' does not appear to be a valid URL?", e)
  exit(1)
end
