#!/usr/bin/env bash

# Initialize asdf
source "$HOME/.asdf/asdf.sh"

# skip if gp is not installed
hash gp 2>/dev/null || return

cd /workspace/gitlab-development-kit

# set RAILS_HOSTS for Gitpod
port=$(gdk config get port)
rails_hosts=$(gp url "${port}" | sed -e 's+^http[s]*://++')
export RAILS_HOSTS=$rails_hosts

# set DEV_SERVER_PUBLIC_ADDR
# This allows to provide 
webpack_port=$(gdk config get webpack.port)
webpack_url=$(gp url "${webpack_port}" | sed -e 's+^http[s]*://+wss://+')/ws
export DEV_SERVER_PUBLIC_ADDR=$webpack_url
export DEV_SERVER_ALLOWED_HOSTS=$rails_hosts