#!/bin/sh

GITPOD_WORKSPACE_IMAGE="${GITPOD_WORKSPACE_IMAGE:-gitpod-image}"
# test
cd ./support/gitpod || exit 1
echo "Building ${GITPOD_WORKSPACE_IMAGE}"
DOCKER_BUILDKIT=1 docker build --progress=plain --build-arg git_checkout_branch="${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-${CI_COMMIT_SHA}}" --tag "${GITPOD_WORKSPACE_IMAGE}" .

if [[ "$CI" == "true" ]]; then
  docker push "${GITPOD_WORKSPACE_IMAGE}"
fi
