#!/bin/sh
GITPOD_WORKSPACE_IMAGE="${GITPOD_WORKSPACE_IMAGE:-gitpod-image}"

cd ./support/gitpod || exit 1
echo "Building ${GITPOD_WORKSPACE_IMAGE}"
DOCKER_BUILDKIT=0 docker build --progress=plain --tag "${GITPOD_WORKSPACE_IMAGE}" .

if [ "$CI" = "true" ]; then
  docker push "${GITPOD_WORKSPACE_IMAGE}"
fi
