#!/bin/sh

GITLAB_REMOTE_WORKSPACE_IMAGE="${GITLAB_REMOTE_WORKSPACE_IMAGE:-gitlab-remote-development-image}"

cd ./support/gitlab-remote-development || exit 1
echo "Building ${GITLAB_REMOTE_WORKSPACE_IMAGE}"
docker build \
  --progress=plain \
  --build-arg git_checkout_branch="${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-${CI_COMMIT_SHA}}" \
  --build-arg git_remote_origin_url="${CI_MERGE_REQUEST_SOURCE_PROJECT_URL:-}" \
  --tag "${GITLAB_REMOTE_WORKSPACE_IMAGE}" .

if [ "$CI" = "true" ]; then
  docker push "${GITLAB_REMOTE_WORKSPACE_IMAGE}"
fi
