schemaVersion: 2.2.0
components:
  - name: tooling-container
    attributes:
      gl/inject-editor: true
    container:
      image: registry.gitlab.com/gitlab-org/gitlab-development-kit/gitlab-remote-workspace:main
      memoryRequest: 10240M
      memoryLimit: 16384M
      cpuRequest: 2000m
      cpuLimit: 6000m
      endpoints:
        - name: ssh-2222
          targetPort: 2222
        - name: gdk-3000
          targetPort: 3000
        - name: docs-3005
          targetPort: 3005
        - name: pages-3010
          targetPort: 3010
        - name: webpack-3808
          targetPort: 3808
        - name: registry-5000
          targetPort: 5000
        - name: jaeger-5778
          targetPort: 5778
        - name: objects-9000
          targetPort: 9000
