image: registry.gitlab.com/gitlab-org/gitlab-development-kit/gitpod-workspace:stable

tasks:

  - name: GDK
    command: |
      echo START_TIME_IN_SECONDS="$(date +%s)" | tee /workspace/gitpod_start_time.sh
      gp sync-done gitpod-start
      gp sync-await gdk-copied && cd /workspace/gitlab-development-kit && gdk help

  - init: |
      echo "$(date) – Copying GDK" | tee -a /workspace/startup.log
      cp -r $HOME/gitlab-development-kit /workspace/
      (
        set -e
        ./gitpod-init
      )
    command: |
      (
        gp sync-await gitpod-start
        set -e
        gp sync-done gdk-copied
        ./gitpod-command
      )

ports:
  - port: 2222  # sshd
    onOpen: ignore
  - port: 3000  # rails-web
    onOpen: notify
  - port: 3005  # gitlab-docs
    onOpen: notify
  - port: 3010  # gitlab-pages
    onOpen: ignore
  - port: 3808  # webpack
    onOpen: ignore
  - port: 5000  # auto_devops
    onOpen: ignore
  - port: 5778  # jaeger
    onOpen: ignore
  - port: 9000  # object_store / minio
    onOpen: ignore
  - port: 9122  # gitlab-shell
    onOpen: ignore

vscode:
  extensions:
    - rebornix.ruby@0.28.0
    - wingrunr21.vscode-ruby@0.27.0
    - karunamurti.haml@1.3.1
    - octref.vetur@0.34.1
    - dbaeumer.vscode-eslint@2.1.8
    - gitlab.gitlab-workflow@3.24.0
    - DavidAnson.vscode-markdownlint@0.44.4