# bootstrap docker compose file
version: '3'
services:
  redis:
    image: "redis:3.0.7-alpine"
    network_mode: host
  postgres:
    image: "postgres:9.6.1-alpine"
    network_mode: host
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
  gitlab-development-kit:
    build: .
    image: gdk
    network_mode: host
    volumes:
      - ./gitlab/:/home/gdk/gitlab-development-kit/gitlab
      - ./go-gitlab-shell/:/home/gdk/gitlab-development-kit/go-gitlab-shell
      - ./gitlab-workhorse/:/home/gdk/gitlab-development-kit/gitlab-workhorse
      - ./gitaly/:/home/gdk/gitlab-development-kit/gitaly
    depends_on:
      - postgres
      - redis
