# bootstrap docker compose file
version: '3'
services:
  redis:
    image: "redis:4.0-alpine"
  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data
  gitlab-development-kit:
    build:
      context: .
      dockerfile: compose/Dockerfile
    image: gdk
    volumes:
      - ./gitlab/:/home/gdk/gitlab-development-kit/gitlab
      - ./go-gitlab-shell/:/home/gdk/gitlab-development-kit/go-gitlab-shell
      - ./gitlab-workhorse/:/home/gdk/gitlab-development-kit/gitlab-workhorse
      - ./gitaly/:/home/gdk/gitlab-development-kit/gitaly
    depends_on:
      - postgres
      - redis
