# bootstrap docker compose file
version: '3'
services:
  redis:
    image: "redis:3.0.7-alpine"
    network_mode: host
  postgres:
    image: "postgres:9.6.1-alpine"
    network_mode: host
  gitlab-development-kit-base:
    build: base
    image: gdk-base
  gitlab-development-kit:
    build: .
    image: gdk
    network_mode: host
    volumes:
      - gitlab/:/home/gdk/gitlab-development-kit
      - go-gitlab-shell/:/home/gdk/go-gitlab-shell
      - gitlab-runner/:/home/gdk/gitlab-runner
    depends_on:
      - gitlab-development-kit-base
    command: gdk run
