#!/bin/bash -e

bootstrap_asdf() {
  # Install asdf plugins, e.g. `asdf plugin add ruby`
  if [[ "$OSTYPE" == "darwin"* ]]; then
    xargs_extra_args=""
  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    xargs_extra_args="-r"
  else
    echo "ERROR: Unsupported platform."
    exit 1
  fi

  comm -23 <(cut -d ' ' -f 1 .tool-versions | sort) <(asdf plugin list | sort) | xargs ${xargs_extra_args} -tn1 asdf plugin add

  # Install all packages specified in .tool-versions
  MAKELEVEL=0 asdf install
}

bootstrap_gdk() {
  gem install bundler -v '= 1.17.3'
  gem install gitlab-development-kit
}

bootstrap_asdf
bootstrap_gdk
