#!/bin/sh

execute_command() {
  command="${*}"

  echo "${command}"
  echo "-------------------------------------------------------------------------------"
  eval "${command}"
  echo
}

if [ "${GDK_DEBUG}" = "1" ] || [ "${GDK_DEBUG}" = "true" ]; then
  execute_command whoami
  execute_command ulimit -a
  execute_command /sbin/sysctl -a
  execute_command nproc
  execute_command df -h
  execute_command free -m
  execute_command 'env | grep -Ev "TOKEN|PASSWORD|LICENSE|KEY"'
  execute_command pwd
  execute_command ls -la
fi

true
