#!/bin/sh

execute_command() {
  command="${*}"

  echo "${command}"
  echo "-------------------------------------------------------------------------------"

  if command -v "${1}" > /dev/null 2>&1; then
    eval "${command}"
  else
    echo "WARNING: '${1}' is not available on this platform."
  fi

  echo
}

if [ "${GDK_DEBUG}" = "1" ] || [ "${GDK_DEBUG}" = "true" ]; then
  execute_command ulimit -a
  execute_command /sbin/sysctl -a
  execute_command nproc
  execute_command df -h
  execute_command free -m
  execute_command env
fi
