#!/bin/bash -e
set -e

ROOT_PATH="$(cd "$(dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")/../.." || exit ; pwd -P)"
DOCKER_IMAGE=registry.gitlab.com/gitlab-org/gitlab-development-kit/gitpod-workspace:main
HOME=/home/gitpod

if ! docker run --rm -t \
  -v "${ROOT_PATH}/support/gitpod/startup-scripts/:/tmp/startup-scripts" \
  $DOCKER_IMAGE \
  bash -ic "/tmp/startup-scripts/; /tmp/startup-scripts/docker-entrypoint;"; 
then
  echo "ERROR: Failed to run Gitlab in Gitpod workspace docker image." >&2
  exit 1
else
  echo "INFO: Successfully runs GitLab in Gitpod workspace docker image."
fi