#!/bin/bash -e

output=$(support/asdf-combine)

if ! git diff --exit-code .tool-versions; then
  echo
  echo "ERROR: There are .tool-versions changes that need to be checked in.  Run 'support/asdf-combine' to generate."
  echo "INFO: Output from support/asdf-combine:"
  echo "${output}"
  exit 1
fi
