#!/bin/bash -e

support/asdf-combine

git diff --exit-code .tool-versions
result=$?

if [[ ${result} != 0 ]]; then
  echo
  echo "ERROR: There are .tool-versions changes that need to be checked in.  Run 'support/asdf-combine' to generate."
  exit ${result}
fi
