#!/bin/bash -e

parent_path=$(dirname "$0")

# shellcheck source=support/ci/functions.sh
source "${parent_path}"/functions.sh

init

# test GDK install
if [ -n "${1}" ]; then
  checkout "${1}"
else
  if [ -n "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}" ]; then
    checkout "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
  else
    checkout "${CI_COMMIT_SHA}"
  fi
fi

install_gem
install
start
test_url

# test GDK self-update
if [ -n "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}" ]; then
  checkout "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
else
  checkout "${CI_COMMIT_SHA}"
fi

restart
test_url

# test GDK components update
install_gem
update
doctor
test_url
