#!/bin/bash -ex

parent_path=$(dirname "$0")

# shellcheck source=support/ci/functions.sh
source "${parent_path}"/functions.sh

export PATH=/usr/local/go/bin:${PATH}

apt update && apt install -y sudo make runit exiftool
support/bootstrap-packages

init

if [ -n "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}" ]; then
  checkout "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
else
  checkout "${CI_COMMIT_SHA}"
fi

install_gem
install
doctor
start
wait_for_boot
QUIET=false "${parent_path}"/../test_url
