#!/usr/bin/env bash

set -euo pipefail

ssh-keygen -t ed25519 -C "GDK-in-a-box" -N "" -f /home/debian/.ssh/id_ed25519 -q
cd ~/gitlab-development-kit/gitlab
echo "What is your name?"
read -r name </dev/tty
echo "What is your e-mail address?"
read -r email </dev/tty
git remote set-url --push origin git@gitlab.com:gitlab-community/gitlab.git
git config --global user.email "$email"
git config --global user.name "$name"
echo "Please add this key to your profile https://gitlab.com/-/profile/keys"
cat ~/.ssh/id_ed25519.pub