.build-job:
  stage: build
  extends:
    - .docker:build-docker-in-docker
  tags:
    - gitlab-org
    - high-cpu

release-image:
  extends:
    - .rules:code-changes
    - .build-job
  script:
    - ./support/docker ci-build-if-necessary

build-gitpod-workspace-image:
  extends:
    - .build-job
    - .rules:gitpod-code-changes
  script:
    - ./support/gitpod/docker-build
