.build-job:
  stage: build
  extends:
    - .docker:build-docker-in-docker
  tags:
    - gitlab-org
    - high-cpu

release-image:
  extends:
    - .rules:code-changes
    - .build-job
  script:
    - ./support/docker ci-build-if-necessary

build-gitpod-workspace-image:
  extends:
    - .build-job
  script:
    - ./support/gitpod/docker-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_MERGE_REQUEST_IID'
      changes:
        - "support/gitpod/**/*"
