.build-job:
  stage: build
  extends:
    - .docker:build-docker-in-docker
  tags:
    - gitlab-org-docker

release-image:
  extends:
    - .rules:code-changes
    - .build-job
  script:
    - ./support/docker ci-build-if-necessary

build-gitpod-workspace-image:
  extends:
    - .build-job
    - .rules:gitpod-code-changes
  script:
    - ./support/gitpod/docker-build

build-gitlab-remote-workspace-image:
  extends:
    - .build-job
    - .rules:gitlab-remote-code-changes
  script:
    - ./support/gitlab-remote-development/docker-build
