.deploy-job:
  stage: deploy

yard:
  extends: .deploy-job
  image: ruby:2.7
  script:
    - bundle install
    - bundle exec yardoc
  cache:
    key: "ruby-2.7-bundle"
    paths:
      - $BUNDLE_PATH
  artifacts:
    expire_in: 1 week
    paths:
      - yard/*

pages:
  extends: .deploy-job
  needs:
    - job: yard
      artifacts: true
  script:
    - cp -r yard public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy-gitpod-workspace-image:
  extends:
    - .deploy-job
    - .docker:build-docker-in-docker
  needs:
    - build-gitpod-workspace-image
  script:
    - ./support/gitpod/docker-tag-image-as-stable
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: manual
