deploy-gitpod-workspace-image:
  stage: post
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Hello Gitpod!"
  rules:
    - if: '$CI_COMMIT_BRANCH == "gitpod-workspace-image" || $CI_COMMIT_TAG'
