deploy-gitpod-workspace-image:
  extends:
    # - .rules:code-changes
    - .docker:use-docker-in-docker
  image: docker:git
  stage: post
  before_script:
    - apk add --no-cache jq curl
  script:
    - ./support/docker ci-login
    - ./support/gitpod/docker-build
  after_script:
    - ./support/docker ci-logout
