.verify-job-macos:
  stage: verify
  extends: .rules:code-changes
  image: macos-12-xcode-13
  needs:
    - []
  tags:
    - shared-macos-amd64
  variables:
    BUNDLE_PATH: "$CI_PROJECT_DIR/.bundle"
  cache:
    key:
      prefix: "gdk-verify-job-macos"
      files:
        - .tool-versions
    paths:
      - ".bundle"
      - ".asdf"
      - ".usr_local"
  artifacts:
    paths:
      - ./gdk/gitlab/log/*.log
      - ./gdk/log
      - ./gdk/sv/*/run
    expire_in: 2 days
    when: always

install-macos:
  extends: .verify-job-macos
  variables:
    GDK_DEBUG: 'true'
  script:
    #- rsync -ax .usr_local/ /usr/local/ || true

    - time /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - source support/bootstrap-prep
    - time make bootstrap

    #- rsync -ax --delete-after /usr/local/ .usr_local/ || true

    #- support/ci/verify-install
